KS-20-5 Solving task number 5
DrraGor/KotlinSprint pull request #122
Opened 2023-05-07 11:39 UTC by DrraGor

2023-05-11 16:39 UTC, ievetrov requested changes

2023-05-11 17:58 UTC, DrraGor commented on src/main/kotlin/lesson_20/lesson20_task5.kt
> +class RobotLesson20() {
) упустил, поправил.

2023-05-12 16:24 UTC, ievetrov requested changes

2023-05-13 11:40 UTC, DrraGor commented on src/main/kotlin/lesson_20/lesson20_task5.kt
> +    robot.setModifier { println(robot.say().reversed()) }
Извините как-то умудрился пропустить. Исправил.

2023-05-13 21:18 UTC, ievetrov requested changes

2023-05-14 14:25 UTC, DrraGor commented on src/main/kotlin/lesson_20/lesson20_task5.kt
> +    var lambdaForSay = { phrasesList.random() }
Не могу сообразить как это сделать (

2023-05-17 17:48 UTC, ievetrov requested changes

2023-05-17 20:44 UTC, ievetrov approved these changes
красивое) аппрув!

2023-05-17 20:55 UTC, merged